=== rnfxl92/2012920022_SungMin/S33-240r0-A331-schemas-for-S33-331r0/SLT-1.0-20170922.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:slt="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/SLT/1.0/" xmlns:sa="tag:atsc.org,2016:XMLSchemas/ATSC3/SA/1.0/" targetNamespace="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/SLT/1.0/" elementFormDefault="qualified">
	<xs:import namespace="tag:atsc.org,2016:XMLSchemas/ATSC3/SA/1.0/" schemaLocation="SA-1.0-20170921.xsd"/>
	<xs:element name="SLT" type="slt:sltType"/>
	<xs:complexType name="sltType">
		<xs:sequence>
			<xs:element name="SLTCapabilities" type="sa:CapabilitiesType" minOccurs="0"/>
			<xs:element name="SLTInetUrl" type="slt:URLType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Service" type="slt:serviceType" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="bsid" type="slt:listOfUnsignedShortType" use="required"/>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:complexType name="serviceType">
		<xs:sequence>
			<xs:element name="SimulcastTSID" type="slt:SimulcastTSIDType" minOccurs="0"/>
			<xs:element name="SvcCapabilities" type="sa:CapabilitiesType" minOccurs="0"/>
			<xs:element name="BroadcastSvcSignaling" type="slt:broadcastSigType" minOccurs="0"/>
			<xs:element name="SvcInetUrl" type="slt:URLType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="OtherBsid" type="slt:OtherBsidType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="serviceId" type="xs:unsignedShort" use="required"/>
		<xs:attribute name="globalServiceID" type="xs:anyURI"/>
		<xs:attribute name="sltSvcSeqNum" type="xs:unsignedByte" use="required"/>
		<xs:attribute name="protected" type="xs:boolean" default="false"/>
		<xs:attribute name="majorChannelNo" type="slt:ChannelNumType"/>
		<xs:attribute name="minorChannelNo" type="slt:ChannelNumType"/>
		<xs:attribute name="serviceCategory" type="xs:unsignedByte" use="required"/>
		<xs:attribute name="shortServiceName" type="xs:string"/>
		<xs:attribute name="hidden" type="xs:boolean" default="false"/>
		<xs:attribute name="broadbandAccessRequired" type="xs:boolean" default="false"/>
		<xs:attribute name="essential" type="xs:boolean"/>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:complexType name="SimulcastTSIDType">
		<xs:simpleContent>
			<xs:extension base="xs:unsignedShort">
				<xs:attribute name="simulcastMajorChannelNo" type="slt:ChannelNumType"/>
				<xs:attribute name="simulcastMinorChannelNo" type="slt:ChannelNumType"/>
				<xs:anyAttribute processContents="strict"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="broadcastSigType">
		<xs:attribute name="slsProtocol" type="xs:unsignedByte" use="required"/>
		<xs:attribute name="slsMajorProtocolVersion" type="xs:unsignedByte" default="1"/>
		<xs:attribute name="slsMinorProtocolVersion" type="xs:unsignedByte" default="0"/>
		<xs:attribute name="slsDestinationIpAddress" type="slt:IPv4addressType" use="required"/>
		<xs:attribute name="slsDestinationUdpPort" type="slt:PortType" use="required"/>
		<xs:attribute name="slsSourceIpAddress" type="slt:IPv4addressType"/>
		<xs:anyAttribute processContents="strict"/>
	</xs:complexType>
	<xs:complexType name="URLType">
		<xs:simpleContent>
			<xs:extension base="xs:anyURI">
				<xs:attribute name="urlType" type="xs:unsignedByte" use="required"/>
				<xs:anyAttribute processContents="strict"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="OtherBsidType">
		<xs:simpleContent>
			<xs:extension base="slt:listOfUnsignedShortType">
				<xs:attribute name="type" type="xs:unsignedByte" use="required"/>
				<xs:anyAttribute processContents="strict"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="ChannelNumType">
		<xs:restriction base="xs:unsignedShort">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IPv4addressType">
		<xs:restriction base="xs:token">
			<xs:pattern value="(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PortType">
		<xs:restriction base="xs:unsignedShort">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="listOfUnsignedShortType">
		<xs:list itemType="xs:unsignedShort"/>
	</xs:simpleType>
</xs:schema>

=== rnfxl92/2012920022_SungMin/S33-240r0-A331-schemas-for-S33-331r0/SLT-Example-20170922.xml
<?xml version="1.0" encoding="UTF-8"?>
<SLT
xmlns="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/SLT/1.0/"
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation= "tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/SLT/1.0/ SLT-1.0-20170922.xsd"
bsid="1234 5678">
	<SLTCapabilities>?????</SLTCapabilities>
	<SLTInetUrl urlType="1">http://www.user.com</SLTInetUrl>
	<Service serviceId="1" globalServiceID="mytv.com/8.2" sltSvcSeqNum="0" protected="true" majorChannelNo="8" minorChannelNo="1"
		 serviceCategory="1" shortServiceName="KUSER" hidden="true" broadbandAccessRequired="true"
		 essential="true">
		<SimulcastTSID simulcastMajorChannelNo="2" simulcastMinorChannelNo="1">4321</SimulcastTSID>
		<SvcCapabilities>?????</SvcCapabilities>
		<BroadcastSvcSignaling slsProtocol="1" slsMajorProtocolVersion="1" slsMinorProtocolVersion="0"
			slsDestinationIpAddress="1.2.3.4" slsDestinationUdpPort="99" slsSourceIpAddress="5.6.7.8"/>
		<SvcInetUrl urlType="1">http://www.user.com</SvcInetUrl>
		<OtherBsid type="1">4321 9876</OtherBsid>
	</Service>
	<Service serviceId="2" sltSvcSeqNum="0" serviceCategory="1"/>
</SLT>

=== rnfxl92/2012920022_SungMin/S33-240r0-A331-schemas-for-S33-331r0/SLT-Example2-20170922.xml
<?xml version="1.0" encoding="UTF-8"?>
<slt:SLT bsid="65535" xsi:schemaLocation="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/SLT/1.0/ SLT-1.0-20170922.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:slt="tag:atsc.org,2016:XMLSchemas/ATSC3/Delivery/SLT/1.0/">
	<slt:SLTCapabilities>String</slt:SLTCapabilities>
	<slt:SLTInetUrl urlType="255">http://www.wxyz.com</slt:SLTInetUrl>
	<slt:Service protected="false" majorChannelNo="7" serviceId="23423" globalServiceID="wxyz.com/7.1" minorChannelNo="1" sltSvcSeqNum="1" serviceCategory="255" shortServiceName="WXYZ-7.1">
		<slt:SimulcastTSID simulcastMinorChannelNo="1" simulcastMajorChannelNo="7">65535</slt:SimulcastTSID>
		<slt:BroadcastSvcSignaling slsSourceIpAddress="239.255.7.1" slsDestinationUdpPort="1" slsProtocol="1" slsDestinationIpAddress="239.255.7.1"/>
		<slt:SvcInetUrl urlType="255">http://www.wxyz.com</slt:SvcInetUrl>
	</slt:Service>
	<slt:Service protected="false" majorChannelNo="7" serviceId="23424" globalServiceID="wxyz.com/7.2" minorChannelNo="2" essential="true" sltSvcSeqNum="255" serviceCategory="255" shortServiceName="WXYZ-7.2">
		<slt:SimulcastTSID simulcastMinorChannelNo="2" simulcastMajorChannelNo="7">65535</slt:SimulcastTSID>
		<slt:BroadcastSvcSignaling slsSourceIpAddress="239.255.7.2" slsDestinationUdpPort="1" slsProtocol="1" slsDestinationIpAddress="239.255.7.2"/>
		<slt:SvcInetUrl urlType="255">http://www.wxyz.com</slt:SvcInetUrl>
	</slt:Service>
	<slt:Service protected="false" majorChannelNo="7" serviceId="23425" globalServiceID="wxyz.com/7.3" minorChannelNo="3" sltSvcSeqNum="6" serviceCategory="255" shortServiceName="WXYZ-7.3">
		<slt:SimulcastTSID simulcastMinorChannelNo="3" simulcastMajorChannelNo="7">65535</slt:SimulcastTSID>
		<slt:BroadcastSvcSignaling slsSourceIpAddress="239.255.7.3" slsDestinationUdpPort="1" slsProtocol="1" slsDestinationIpAddress="239.255.7.3"/>
		<slt:SvcInetUrl urlType="255">http://www.wxyz.com</slt:SvcInetUrl>
		<slt:OtherBsid type="255">65535</slt:OtherBsid>
	</slt:Service>
	<slt:Service protected="false" majorChannelNo="7" serviceId="23426" globalServiceID="wxyz.com/7.4" minorChannelNo="4" sltSvcSeqNum="66" serviceCategory="255" shortServiceName="WXYZ-7.4">
		<slt:SimulcastTSID simulcastMinorChannelNo="4" simulcastMajorChannelNo="7">65535</slt:SimulcastTSID>
		<slt:SvcCapabilities>0700</slt:SvcCapabilities>
		<slt:BroadcastSvcSignaling slsSourceIpAddress="239.255.7.4" slsDestinationUdpPort="1" slsProtocol="1" slsDestinationIpAddress="239.255.7.4"/>
		<slt:SvcInetUrl urlType="255">http://www.wxyz.com</slt:SvcInetUrl>
		<slt:OtherBsid type="255">65535</slt:OtherBsid>
	</slt:Service>
	<slt:Service protected="false" majorChannelNo="7" serviceId="23427" globalServiceID="wxyz.com/7.5" broadbandAccessRequired="true" minorChannelNo="5" sltSvcSeqNum="14" serviceCategory="255" shortServiceName="WXYZ-7.5">
		<slt:SimulcastTSID simulcastMinorChannelNo="5" simulcastMajorChannelNo="7">65535</slt:SimulcastTSID>
		<slt:SvcCapabilities>0700</slt:SvcCapabilities>
		<slt:BroadcastSvcSignaling slsSourceIpAddress="239.255.7.5" slsDestinationUdpPort="1" slsProtocol="1" slsDestinationIpAddress="239.255.7.5"/>
		<slt:SvcInetUrl urlType="255">http://www.wxyz.com</slt:SvcInetUrl>
		<slt:OtherBsid type="255">65535</slt:OtherBsid>
	</slt:Service>
</slt:SLT>
